name: Automations

on:
  push:
    branches: [main]
  paths:
    - .github/spec/label.yml

jobs:
  label-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/spec/label.yml
