name: Setting Specification

on:
  push:
    branches:
      - main
    paths:
      - .github/settings.yml
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  setting-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: mooseburgr/repository-settings-action@v1
        with:
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          settings-path: https://raw.githubusercontent.com/TSLedger/.github/refs/heads/main/.github/spec/setting.yml
